services:
  web:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 3001
      WATCHPACK_POLLING: true
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules